version: "3"
networks:
  laravel:
    driver: bridge
volumes:
  postgres_db:
    driver: local
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "7000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app:delegated
    depends_on:
      - php
    networks:
      - laravel
  postgres:
    image: postgres:16.4-alpine3.20
    container_name: postgres-laravel
    restart: always
    ports:
      - "5435:5432"
    volumes: 
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    depends_on:
      - postgres
    expose:
      - "9000"
    volumes:
      - .:/var/www/app:delegated
    networks:
      - laravel
    command: sh -c "./wait-for-it.sh postgres:5432 -- php artisan migrate:install && php artisan migrate --force && php-fpm"

